apollographql/eslint-plugin-graphql

src/index.js

disable `NoUndefinedVariables` when using relay

---

README.md
src/index.js

I'm using this plugin with Atom in isomorphic app. And my webpack configuration may change/regenerate `graphql.schema.json` file on the fly.
So for me is not a good solution to provide schema object via `.eslintrc.js`. So this PR adds an ability to provide an absolute path to the graphql schema json file.
My `.eslintrc.js` with this PR looks like
```js
const path = require('path');
module.exports = {
"env": {
"node": true,
"es6": true,
"browser": true,
},
"parser": "babel-eslint",
"extends": "airbnb",
"plugins": [
"import",
"graphql"
],
"settings": {
"import/resolver": {
"babel-module": {}
}
},
"globals": {
"__DEV__": true
},
"rules": {
"graphql/template-strings": ['error', {
env: 'relay',
// schemaJson: require('./build/schema.graphql.json'),
schemaJsonFilepath: path.resolve(__dirname, …
```

Add option `schemaJsonFilepath` which allows set up absolute path to the graphql json file.

---

src/index.js

Sorry for the inconvenience. I don't know how it happens, but I somehow missed `import fs from 'fs';` in my previous PR https://github.com/apollostack/eslint-plugin-graphql/pull/20 (which on npm right now). 😇
Please merge and bump new version. Thanks.

Fix required fs import for `schemaJsonFilepath` option

---

README.md
src/index.js
test/index.js
test/makeProcessors.js

I ran into the issue where I want to lint my *.gql files so I can use graphql-tag loader for webpack.
Open points:
- I do not see any possibility to access the plugins configuration in `processors`
- I am new to eslint plugins and asking for advice regarding testing
closes #25

enable linting of *.gql *.graphql when using gql tag

---

.gitignore
README.md
src/index.js
test/makeRule.js
test/second-schema.graphql
test/updateSchemaJson.js

This is a backwards-compatible change which supports multiple option groups being passed in. Tags must be unique and can refer to different schemas.
This is useful for codebases that interact with multiple GraphQL endpoints. In our case, we have multiple backend services exposing their own GraphQL schemas, and this allows us to lint their usage via backend-specific tags.
For example:
```js
const FooQuery = Foo.gql`{ foos(first: 10) { id } }`;
const BarQuery = Bar.gql`{ bars(last: 10) { name } }`;
```
via the configuration:
```js
module.exports = {
"parser": "babel-eslint",
"rules": {
"graphql/template-strings": ['error', {
env: 'apollo',
tagName: 'Foo.gql',
schemaJson: require('./foo-schema.json')
}, {
env: 'relay',
tagName: 'Bar.gql',
schemaJson: require('./bar-schema.json')
}]
}, …
```

Support validation against multiple schemas.

---

README.md
src/index.js
test/makeRule.js
test/schema.graphql

This adds support for configurable selection of GraphQL validators.
The addition is fully backwards-compatible for configurations that specified a value for `env`.
For configurations that did not set `env`, all validators are now enabled by default. This is a slight change because `KnownFragmentNames` and `NoUnusedFragments` had been disabled entirely for reasons that appear specific to Lokka.
Resolves apollostack/eslint-plugin-graphql#10

Add support for custom selection of validators.

---

src/index.js
test/makeRule.js

This PR is attempting to resolve #29.
In Apollo, fragment interpolation is now valid within the `gql` TaggedTemplateLiteral, but only outside of top-level structures like `query` or `mutation`. In other clients like Lokka and Relay, fragment interpolation actually results in a document substitution, but in Apollo this gets evaluated at runtime, so we only need to validate the location of the fragment interpolation.
We'll do this by evaluating two things:
1.  Making sure that an error isn't thrown when a valid interpolation is found
2. Throwing an error when an invalid interpolation _is_ found
In Apollo, fragment interpolation is invalid inside of query structures, so a document like this should fail:
```js
gql`query { someField ${SomeFragment} }`
```
NOTE: the evaluation strategy for …

Taking into account Apollo fragment interpolation

---

package.json
test/makeRule.js

Main benefit of this update is better error messages e.g.
```
'Cannot query field "allFilmsx" on type "RootQuery". Did you mean "allFilms"?'
```
TODO:

Update graphql to 0.8.2

---

package.json

0.9.0 was released today - https://github.com/graphql/graphql-js/releases/tag/v0.9.0

Bump graphql to 0.9.0

---

package.json

*TL;DR* This leaks through to downstream builds/packages, so moving it out. 
In my use-case: `jest` sees that there's a `babel-polyfill` package in `node_modules`, and uses it. In a CI environment this hits a particular memory issue wherein our box runs out of available heap for tests to run, and tests die.
I think `babel-polyfill`'s inclusion into `dependencies` _may_ be accidental, however it should really only be included in dev and not downstream packages.

Moving babel-polyfill into devDependencies as it's adding bloat

---

src/index.js
src/rules.js
test/makeRule.js

Adds a lint rule that enforces all operations are named. See https://github.com/apollographql/eslint-plugin-graphql/issues/42 and https://apollographql.slack.com/archives/eslint-plugin-graphql/p1488999103000014.
This adds it as a separate rule: `graphql/named-operations` so that it's easier for folks to configure it on or off / warn vs error. Did a little restructuring to be more DRY
TODO:

Add OperationsMustHaveNames lint rule

---

CHANGELOG.md
README.md
src/index.js
src/rules.js
test/makeRule.js
test/schema.graphql

We have a need to validate that the queries include a `uuid` field, since that's how we cache things client side. I thought I'd try to make this more generic, as a 'required field' lint rule that errors if the field is 1) present in the schema and 2) not requested in this query.
Is this something that you think is worth including in this package? 
Can you offer any guidance on how to pass the rule's options to the rule itself? The rule is invoked within graphql's `validate`, so I'm not seeing a clear way to do this. 
TODO:

Lint for required fields [WIP]

---

CHANGELOG.md
src/rules.js
test/makeRule.js

Fixes https://github.com/apollographql/eslint-plugin-graphql/issues/63
TODO:

fix(required-fields): don't throw on non-existent field

---

CHANGELOG.md
src/index.js

Literal .graphql file imports are not properly reconciled, and the KnownFragmentNames and NoUnusedFragment rules will fail. This removes them from the default rules for the literal env. This is a band-aid toward #69 
Note: Did not see any tests for the default rules used by envs (tests for `literal` generally). Happy to provide test coverage, but please advise on what kind of test you'd like to see for this :)
TODO:

In 'literal' env, don't validate that fragments exist or are used

---

CHANGELOG.md
package.json
src/index.js
test/index.js
test/makeRule.js
yarn.lock

Also removes `babel-polyfill` in favor of `transform-runtime` to surface these runtime-specific issues in testing.
@stubailo 👀  please
TODO:
;)

Remove use of Array.prototype.includes to support older runtimes

---

README.md
src/index.js
test/makeRule.js

Attempted fix for #59. Could you please let me know if this is looks appropriate and what's expected in terms of test?
TODO:

Add option to pass schema as string, fixes #59

---

.gitignore
CHANGELOG.md
README.md
src/index.js
test/__fixtures__/required-fields-invalid-array.graphql
test/__fixtures__/required-fields-invalid-no-id.graphql
test/__fixtures__/required-fields-valid-array.graphql
test/__fixtures__/required-fields-valid-id.graphql
test/__fixtures__/required-fields-valid-no-id.graphql
test/makeProcessors.js
test/makeRule.js

@jnwng :eyes: please 
Allows .graphql and .gql literal files to be linted with the required-fields rule. Resolves #74 
Note: Neglected to update the README when I removed a few broken rules from the `literal` env and just threw the update in here, since I was already at it.
TODO:

Add env option to required-fields rule config

---

CHANGELOG.md
README.md
package.json
src/index.js
test/graphqlconfig/index.js
test/graphqlconfig/multiproject/.graphqlconfig
test/graphqlconfig/simple/.graphqlconfig
test/index.js
yarn.lock

Add support for [`.graphqlconfig`](https://github.com/graphcool/graphql-config)
This PR is backward compatible as it doesn't remove any already existed configuration options. It just adds support for `.graphqlconfig` as a way to configure schema.
That's why I made `schemaJson `, `schemaString` and `schemaJsonFilepath` not required (but they still are mutually exclusive)
cc @jnwng

Add support for .graphqlconfig

---

README.md
src/index.js
src/rules.js
test/makeRule.js

new rule: prefer cap type names

---

CHANGELOG.md
README.md
src/index.js

Eslint config validation

---

CHANGELOG.md
src/index.js
test/makeProcessors.js

Fix escaping of literal .graphql files

---

package.json
yarn.lock

Bumping to `graphql@^0.11`, moving `graphql` to peerDependencies.

---

CHANGELOG.md
README.md
src/index.js
src/rules.js
test/makeRule.js
test/schema.graphql

Hey there! 👋 
#14 describes the need for warnings on deprecated fields which is something I'd like as well so I fiddled around a bit and came up with this that seems to be working in my tests at least. Not sure if I need to make tests for appollo & graphql separately or handle any logic there separately. Also not sure if this should live somewhere else then where I put it. If there should be a rule to opt into or what so I'd appreciate any help on getting this PR up to standard 😄 
TODO:

feat: add a check for deprecation errors

---

package.json
yarn.lock

I still dont have Renovate set up, so manually bumping a couple of libraries that have been giving us some trouble in Node v4/v5. 
Pinning `graphql-config` to `~1.0.0` (no minors) because `1.1.0` introduces a dependency that doesn't quite work in Node v4/v5. I'm imagining that deprecating support for Node v4 should be a major version bump, otherwise we'll wait until both `graphql-config` and `graphql-import` support Node v4/v5/v6.
TODO:
- ~~[ ] Make sure all of the significant new logic is covered by tests~~
- ~~[ ] Update CHANGELOG.md with your change~~
- ~~[ ] If this was a change that affects the external API, update the README~~

Bumping babel-eslint and pinning `graphql-config`

---

src/rules.js
test/makeRule.js
test/schema.graphql

fix bugs in EnumValue

---

README.md
renovate.json

TODO:
**Pull Request Labels**
Based on the list in https://github.com/graphql/graphql-js/blob/master/src/validation/specifiedRules.js.

Update list of available validators (as of GraphQL 0.13.2)

---

CHANGELOG.md
src/index.js

👋 Hey hey!
When working with large GraphQL schemas (like GitHubs v4 API schema) we've noticed that eslint could run a bit slower. We narrowed it down to `eslint-plugin-graphql` adding ~500ms per file to the run time of `eslint`.
By adding a simple cache object for the schema results of `parseOptions` we can bring that time down pretty signifigantly.
Here's a example eslint run in one of our projects at GitHub:
Before this patch:
```
⚡ time TIMING=1 ./node_modules/.bin/eslint .
Rule                            | Time (ms) | Relative
:-------------------------------|----------:|--------:
prettier/prettier               |  5956.319 |    57.1%
graphql/no-deprecated-fields    |  1427.804 |    13.7%
import/namespace                |   810.107 |     7.8%
no-unused-vars                  | …
```

Cache for parsing the schema

---

CHANGELOG.md
src/index.js
test/__fixtures__/required-fields-invalid-no-id.graphql
test/makeProcessors.js
test/makeRule.js

Thanks for maintaining this plugin! I ran into some odd error locations when using it with raw `.graphql` files, and it looks like the ultimate culprit was an off-by-one bug 🙂 
Prior to this change, the contents of tagged strings were having leading and trailing whitespace trimmed before being processed. This masked an off-by-one error in the location calculation for errors after the first line of a document, since the most common usage pattern has a single extra leading line before the actual content which offsets that:
```js
const query = gql`
query ...
`;
```
This meant that standalone `.graphql` files had all their errors displayed on the wrong line (unless they opened with a single blank line as well), and tagged strings with multiple newlines at their start would also have issues. …

Fix error locations for .graphql files and tagged strings with leading newlines

---

src/rules.js
test/makeRule.js

Fixes: https://github.com/apollographql/eslint-plugin-graphql/issues/139

RequiredFields rule supports inline fragments

---

CHANGELOG.md
src/customGraphQLValidationRules.js
test/__fixtures__/required-fields-valid-id.graphql
test/schema.graphql
test/validationRules/required-fields.js

Required fields and fragments

---

CHANGELOG.md
src/index.js
test/graphqlconfig/index.js
test/graphqlconfig/multiproject-literal/.graphqlconfig

TODO:
**Pull Request Labels**
resolves #178

Fix schema caching for multi-schema workspaces

---

CHANGELOG.md
src/customGraphQLValidationRules.js
test/validationRules/required-fields.js

TODO:
Fixes a regression of https://github.com/apollographql/eslint-plugin-graphql/issues/63 introduced in v3.0.0

Fix required fields regression

---

package-lock.json
package.json
test/validationRules/built-in.js

Due to strict string matches between expected error messages and the error messages output by `graphql-js`, these tests were failing. Fortunately, `eslint#RuleTester` will test regular expressions if they're provided, so here I'm boiling down the tests to make sure they work properly across different versions of `graphql-js`
Holistically, I think it's a little difficult to continue to support so many different version of `graphql-js`. I think when `graphql@15.x` comes around, we may need to consider matching majors or splitting out tests based on what version of `graphql-js` is installed.
TODO:
- ~[ ] Make sure all of the significant new logic is covered by tests~
- ~[ ] Rebase your changes on master so that they can be merged easily~

Fixing issues with tests failing using `graphql-js@14.3.0`

---

CHANGELOG.md
src/customGraphQLValidationRules.js
test/validationRules/required-fields.js

Previously, only the first half of the check inside `fieldAvailableOnType` guarded against `type` being `undefined`. This meant that the function would throw an error.
To fix this, and o prevent it from accidentally happening again if we ever add another check to this logic, I moved the check for `!type` up into it's own guard, with an early return.
This change makes the required-fields rule more resilient (which uses this `fieldAvailableOnType` function internally).
Without this change, I see errors when trying to run `eslint-plugin-graphql` against my project:
```
Cannot read property 'ofType' of undefined
TypeError: Cannot read property 'ofType' of undefined
at fieldAvailableOnType (/Code/vitorbal/node_modules/eslint-plugin-graphql/lib/customGraphQLValidationRules.js:33:62)
at …
```

Always guard against undefined type in fieldAvailableOnType

---

CHANGELOG.md
src/customGraphQLValidationRules.js
test/validationRules/required-fields.js

We are planning to use the `required-fields` rule to enforce the `id` field but we have some code that was causing `TypeError: Cannot read property 'selectionSet' of undefined` errors.
I tracked down the issue to the case where an inline fragment is missing a required field but does not have a field ancestor. The existing code for the rule will walk up the ancestors until it finds a field, but an inline fragment can be part of any selection set and not only a field (in our case a fragment definition). This example based on the unit tests should demonstrate the issue:
```graphql
fragment GreetingOrStoryFragment on GreetingOrStory {
... on Greetings {
hello
}
}
```
The `id` field is missing from the inline fragment My fix was just to walk up the ancestors until it fields the first field, …

required-fields: inline fragments without a field ancestor

---

CHANGELOG.md
README.md

This PR improves the identity template literal tag docs:
- Tweaked the text from saying tags are “always” used in Apollo projects to “often”, as there are situations  where tags are not necessary like when making server side queries via `node-fetch` that come up in real world projects.
- Replaced the manual copy paste fake tag code with the suggestion to use [`fake-tag`](https://npm.im/fake-tag). This utility is easy to install and use and has tests covering Interpolations and escapes. It has been reasonably battle tested.
- Mentioned the `/* GraphQL */` comment tag enhancement issue (https://github.com/apollographql/eslint-plugin-graphql/issues/224).
See earlier discussion: https://github.com/apollographql/eslint-plugin-graphql/issues/224#issuecomment-486508146
TODO:

Improve identity template literal tag docs
